NAME = Assignment1.out
# CC = ~/../../opt/homebrew/bin/g++-13
CC = clang++
SRC = AssignmentBag.cpp
all: $(NAME)

$(NAME):
		@$(CC) -o $(NAME) $(SRC)

clean:
		@/bin/rm -rf $(NAME)

fclean: clean

re: fclean all
